# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 5) do

  create_table "articles", :force => true do |t|
    t.column "title",      :string
    t.column "created_at", :datetime
    t.column "user_id",    :integer
  end

  create_table "links", :force => true do |t|
    t.column "article_id",   :integer
    t.column "url",          :string
    t.column "user_id",      :integer
    t.column "position",     :integer
    t.column "published_on", :datetime
  end

end
